apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: demo-voating-app
spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voating-app
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-voating-app
