apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
    app: demo-voating-app
spec:
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voating-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
  replicas: 3