apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: demo-voating-app
spec:
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voating-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
  replicas: 3